name: mars_project
channels:
  - default
  - pytorch
dependencies:
  - python=3.7.*
  - numpy
  - pandas
  - matplotlib
  - pytorch 
  - torchvision 
  - torchaudio
  - jupyter
  - notebook
  - pip
  - pip:
    - planetaryimage