name: mars_project
channels:
  - default
dependencies:
  - python=3.7.*
  - numpy
  - pillow
  - matplotlib
  - jupyter
  - notebook
  - pip
  - pip:
    - planetaryimage
    - wget
    - torch
    - torchvision
    - torchaudio
    - open3d
    - torchmetrics